//
// Created by neel on 1/26/19.
//

#include "basepower.h"

namespace artificialtrainer {
const int kNone = 0;
const int kVariable = 1;
const int kOneHitKo = 2;
const int kUnchanged = 3;

auto BasePower(const Moves &move_name) -> int {
  switch (move_name) {
    case Moves::kAbsorb: return 20;
    case Moves::kAcid: return 40;
    case Moves::kAcidArmor: return kNone;
    case Moves::kAgility: return kNone;
    case Moves::kAmnesia: return kNone;
    case Moves::kAuroraBeam: return 65;
    case Moves::kBarrage: return 15;
    case Moves::kBarrier: return kNone;
    case Moves::kBide: return kVariable;
    case Moves::kBind: return 15;
    case Moves::kBite: return 60;
    case Moves::kBlizard: return 120;
    case Moves::kBodySlam: return 85;
    case Moves::kBoneClub: return 65;
    case Moves::kBonemerang: return 60;
    case Moves::kBubble: return 20;
    case Moves::kBubbleBeam: return 65;
    case Moves::kClamp: return 35;
    case Moves::kCometPunch: return 18;
    case Moves::kConfuseRay: return kNone;
    case Moves::kConfusion: return 50;
    case Moves::kConstrict: return 10;
    case Moves::kConversion: return kNone;
    case Moves::kCounter: return kVariable;
    case Moves::kCrabhammer: return 90;
    case Moves::kCut: return 50;
    case Moves::kDefenseCurl: return kNone;
    case Moves::kDig: return 100;
    case Moves::kDisable: return kNone;
    case Moves::kDizzyPunch: return 70;
    case Moves::kDoubleKick: return 30;
    case Moves::kDoubleTeam: return kNone;
    case Moves::kDoubleEdge: return 100;
    case Moves::kDoubleSlap: return 15;
    case Moves::kDragonRage: return kUnchanged;
    case Moves::kDreamEater: return 100;
    case Moves::kDrillPick: return 80;
    case Moves::kEarthquake: return 100;
    case Moves::kEggBomb: return 100;
    case Moves::kEmber: return 40;
    case Moves::kExplosion: return 170;
    case Moves::kFireBlast: return 120;
    case Moves::kFirePunch: return 75;
    case Moves::kFireSpin: return 15;
    case Moves::kFissure: return kOneHitKo;
    case Moves::kFlamethrower: return 95;
    case Moves::kFlash: return kNone;
    case Moves::kFly: return 70;
    case Moves::kFocusEnergy: return kNone;
    case Moves::kFuryAttack: return 15;
    case Moves::kFurySwipes: return 10;
    case Moves::kGlare: return kNone;
    case Moves::kGrowl: return kNone;
    case Moves::kGrowth: return kNone;
    case Moves::kGuillotine: return kOneHitKo;
    case Moves::kGust: return 40;
    case Moves::kHarden: return kNone;
    case Moves::kHaze: return kNone;
    case Moves::kHeadbutt: return 70;
    case Moves::kHighJumpKick: return 85;
    case Moves::kHornAttack: return 65;
    case Moves::kHornDrill: return kOneHitKo;
    case Moves::kHydroPump: return 120;
    case Moves::kHyperBeam: return 150;
    case Moves::kHyperFang: return 80;
    case Moves::kHypnosis: return kNone;
    case Moves::kIceBeam: return 95;
    case Moves::kIcePunch: return 75;
    case Moves::kJumpKick: return 70;
    case Moves::kKarateChop: return 55;
    case Moves::kKinesis: return kNone;
    case Moves::kLeechLife: return 20;
    case Moves::kLeechSeed: return kNone;
    case Moves::kLeer: return kNone;
    case Moves::kLick: return 20;
    case Moves::kLightScreen: return kNone;
    case Moves::kLovelyKiss: return kNone;
    case Moves::kLowKick: return 50;
    case Moves::kMeditate: return kNone;
    case Moves::kMegaDrain: return 40;
    case Moves::kMegaKick: return 120;
    case Moves::kMegaPunch: return 80;
    case Moves::kMetronome: return kNone;
    case Moves::kMimic: return kNone;
    case Moves::kMinimize: return kNone;
    case Moves::kMirrorMove: return kNone;
    case Moves::kMist: return kNone;
    case Moves::kNightShade: return kVariable;
    case Moves::kPayDay: return 40;
    case Moves::kPeck: return 35;
    case Moves::kPetalDance: return 70;
    case Moves::kPinMissile: return 14;
    case Moves::kPoisonGas: return kNone;
    case Moves::kPoisonSting: return 15;
    case Moves::kPoisonPowder: return kNone;
    case Moves::kPound: return 40;
    case Moves::kPsybeam: return 65;
    case Moves::kPsychic: return 90;
    case Moves::kPsywave: return kVariable;
    case Moves::kQuickAttack: return 40;
    case Moves::kRage: return 20;
    case Moves::kRazorLeaf: return 55;
    case Moves::kRazorWind: return 80;
    case Moves::kRecover: return kNone;
    case Moves::kReflect: return kNone;
    case Moves::kRest: return kNone;
    case Moves::kRoar: return kNone;
    case Moves::kRockSlide: return 75;
    case Moves::kRockThrow: return 50;
    case Moves::kRollingKick: return 60;
    case Moves::kSandAttack: return kNone;
    case Moves::kScratch: return 40;
    case Moves::kScreech: return kNone;
    case Moves::kSeismicToss: return kVariable;
    case Moves::kSelfDestruct: return 130;
    case Moves::kSharpen: return kNone;
    case Moves::kSing: return kNone;
    case Moves::kSkullBash: return 100;
    case Moves::kSkyAttack: return 140;
    case Moves::kSlam: return 80;
    case Moves::kSlash: return 70;
    case Moves::kSleepPowder: return kNone;
    case Moves::kSludge: return 65;
    case Moves::kSmog: return 20;
    case Moves::kSmokescreen: return kNone;
    case Moves::kSoftBoiled: return kNone;
    case Moves::kSolarBeam: return 120;
    case Moves::kSonicBoom: return kUnchanged;
    case Moves::kSpikeCannon: return 20;
    case Moves::kSplash: return kNone;
    case Moves::kSpore: return kNone;
    case Moves::kStomp: return 65;
    case Moves::kStrength: return 80;
    case Moves::kStringShot: return kNone;
    case Moves::kStruggle: return 50;
    case Moves::kStunSpore: return kNone;
    case Moves::kSubmission: return 80;
    case Moves::kSubstitute: return kNone;
    case Moves::kSuperFang: return kVariable;
    case Moves::kSupersonic: return kNone;
    case Moves::kSurf: return 95;
    case Moves::kSwift: return 60;
    case Moves::kSwordsDance: return kNone;
    case Moves::kTackle: return 35;
    case Moves::kTailWhip: return kNone;
    case Moves::kTakeDown: return 90;
    case Moves::kTeleport: return kNone;
    case Moves::kThrash: return 90;
    case Moves::kThunder: return 120;
    case Moves::kThunderWave: return kNone;
    case Moves::kThunderbolt: return 95;
    case Moves::kThunderPunch: return 75;
    case Moves::kThunderShock: return 40;
    case Moves::kToxic: return kNone;
    case Moves::kTransform: return kNone;
    case Moves::kTriAttack: return 80;
    case Moves::kTwineedle: return 25;
    case Moves::kViceGrip: return 55;
    case Moves::kVineWhip: return 35;
    case Moves::kWaterGun: return 40;
    case Moves::kWaterfall: return 80;
    case Moves::kWhirlwind: return kNone;
    case Moves::kWingAttack: return 35;
    case Moves::kWithdraw: return kNone;
    case Moves::kWrap: return 15;
    case Moves::kPass: return kNone;
    case Moves::kSwitch1: return kNone;
    case Moves::kSwitch2: return kNone;
    case Moves::kSwitch3: return kNone;
    case Moves::kSwitch4: return kNone;
    case Moves::kSwitch5: return kNone;
    case Moves::kSwitch6: return kNone;
    case Moves::kHitSelf: return 40;
    default: break;
  };
}

} //namespace artificialtrainer