//
// Created by neel on 1/26/19.
//

#include <cassert>
#include "pp.h"

namespace artificialtrainer {
const int kUnlimited = 0;

auto Pp(const Moves &move_name) -> int {
  switch (move_name) {
    case Moves::kAbsorb:
      return 20;
    case Moves::kAcid:
      return 30;
    case Moves::kAcidArmor:
      return 40;
    case Moves::kAgility:
      return 30;
    case Moves::kAmnesia:
      return 20;
    case Moves::kAuroraBeam:
      return 20;
    case Moves::kBarrage:
      return 20;
    case Moves::kBarrier:
      return 30;
    case Moves::kBide:
      return 10;
    case Moves::kBind:
      return 20;
    case Moves::kBite:
      return 25;
    case Moves::kBlizzard:
      return 5;
    case Moves::kBodySlam:
      return 15;
    case Moves::kBoneClub:
      return 20;
    case Moves::kBonemerang:
      return 10;
    case Moves::kBubble:
      return 30;
    case Moves::kBubbleBeam:
      return 20;
    case Moves::kClamp:
      return 10;
    case Moves::kCometPunch:
      return 15;
    case Moves::kConfuseRay:
      return 10;
    case Moves::kConfusion:
      return 25;
    case Moves::kConstrict:
      return 35;
    case Moves::kConversion:
      return 30;
    case Moves::kCounter:
      return 20;
    case Moves::kCrabhammer:
      return 10;
    case Moves::kCut:
      return 30;
    case Moves::kDefenseCurl:
      return 40;
    case Moves::kDig:
      return 10;
    case Moves::kDisable:
      return 20;
    case Moves::kDizzyPunch:
      return 10;
    case Moves::kDoubleKick:
      return 30;
    case Moves::kDoubleTeam:
      return 15;
    case Moves::kDoubleEdge:
      return 15;
    case Moves::kDoubleSlap:
      return 10;
    case Moves::kDragonRage:
      return 10;
    case Moves::kDreamEater:
      return 15;
    case Moves::kDrillPeck:
      return 20;
    case Moves::kEarthquake:
      return 10;
    case Moves::kEggBomb:
      return 10;
    case Moves::kEmber:
      return 25;
    case Moves::kExplosion:
      return 5;
    case Moves::kFireBlast:
      return 5;
    case Moves::kFirePunch:
      return 15;
    case Moves::kFireSpin:
      return 15;
    case Moves::kFissure:
      return 5;
    case Moves::kFlamethrower:
      return 15;
    case Moves::kFlash:
      return 20;
    case Moves::kFly:
      return 15;
    case Moves::kFocusEnergy:
      return 30;
    case Moves::kFuryAttack:
      return 20;
    case Moves::kFurySwipes:
      return 15;
    case Moves::kGlare:
      return 30;
    case Moves::kGrowl:
      return 40;
    case Moves::kGrowth:
      return 40;
    case Moves::kGuillotine:
      return 5;
    case Moves::kGust:
      return 35;
    case Moves::kHarden:
      return 30;
    case Moves::kHaze:
      return 30;
    case Moves::kHeadbutt:
      return 15;
    case Moves::kHighJumpKick:
      return 20;
    case Moves::kHornAttack:
      return 25;
    case Moves::kHornDrill:
      return 5;
    case Moves::kHydroPump:
      return 5;
    case Moves::kHyperBeam:
      return 5;
    case Moves::kHyperFang:
      return 15;
    case Moves::kHypnosis:
      return 20;
    case Moves::kIceBeam:
      return 10;
    case Moves::kIcePunch:
      return 15;
    case Moves::kJumpKick:
      return 20;
    case Moves::kKarateChop:
      return 25;
    case Moves::kKinesis:
      return 15;
    case Moves::kLeechLife:
      return 15;
    case Moves::kLeechSeed:
      return 10;
    case Moves::kLeer:
      return 30;
    case Moves::kLick:
      return 30;
    case Moves::kLightScreen:
      return 30;
    case Moves::kLovelyKiss:
      return 10;
    case Moves::kLowKick:
      return 20;
    case Moves::kMeditate:
      return 40;
    case Moves::kMegaDrain:
      return 10;
    case Moves::kMegaKick:
      return 5;
    case Moves::kMegaPunch:
      return 20;
    case Moves::kMetronome:
      return 10;
    case Moves::kMimic:
      return 10;
    case Moves::kMinimize:
      return 20;
    case Moves::kMirrorMove:
      return 20;
    case Moves::kMist:
      return 30;
    case Moves::kNightShade:
      return 15;
    case Moves::kPayDay:
      return 20;
    case Moves::kPeck:
      return 35;
    case Moves::kPetalDance:
      return 20;
    case Moves::kPinMissile:
      return 20;
    case Moves::kPoisonGas:
      return 40;
    case Moves::kPoisonSting:
      return 35;
    case Moves::kPoisonPowder:
      return 35;
    case Moves::kPound:
      return 35;
    case Moves::kPsybeam:
      return 20;
    case Moves::kPsychic:
      return 10;
    case Moves::kPsywave:
      return 15;
    case Moves::kQuickAttack:
      return 30;
    case Moves::kRage:
      return 20;
    case Moves::kRazorLeaf:
      return 25;
    case Moves::kRazorWind:
      return 10;
    case Moves::kRecover:
      return 20;
    case Moves::kReflect:
      return 20;
    case Moves::kRest:
      return 10;
    case Moves::kRoar:
      return 20;
    case Moves::kRockSlide:
      return 10;
    case Moves::kRockThrow:
      return 15;
    case Moves::kRollingKick:
      return 15;
    case Moves::kSandAttack:
      return 15;
    case Moves::kScratch:
      return 35;
    case Moves::kScreech:
      return 10;
    case Moves::kSeismicToss:
      return 20;
    case Moves::kSelfDestruct:
      return 5;
    case Moves::kSharpen:
      return 30;
    case Moves::kSing:
      return 15;
    case Moves::kSkullBash:
      return 15;
    case Moves::kSkyAttack:
      return 5;
    case Moves::kSlam:
      return 20;
    case Moves::kSlash:
      return 20;
    case Moves::kSleepPowder:
      return 15;
    case Moves::kSludge:
      return 20;
    case Moves::kSmog:
      return 20;
    case Moves::kSmokescreen:
      return 20;
    case Moves::kSoftBoiled:
      return 10;
    case Moves::kSolarBeam:
      return 10;
    case Moves::kSonicBoom:
      return 20;
    case Moves::kSpikeCannon:
      return 15;
    case Moves::kSplash:
      return 40;
    case Moves::kSpore:
      return 15;
    case Moves::kStomp:
      return 20;
    case Moves::kStrength:
      return 15;
    case Moves::kStringShot:
      return 40;
    case Moves::kStruggle:
      return 1;
    case Moves::kStunSpore:
      return 30;
    case Moves::kSubmission:
      return 20;
    case Moves::kSubstitute:
      return 10;
    case Moves::kSuperFang:
      return 10;
    case Moves::kSupersonic:
      return 20;
    case Moves::kSurf:
      return 15;
    case Moves::kSwift:
      return 20;
    case Moves::kSwordsDance:
      return 30;
    case Moves::kTackle:
      return 35;
    case Moves::kTailWhip:
      return 30;
    case Moves::kTakeDown:
      return 20;
    case Moves::kTeleport:
      return 20;
    case Moves::kThrash:
      return 20;
    case Moves::kThunder:
      return 10;
    case Moves::kThunderWave:
      return 20;
    case Moves::kThunderbolt:
      return 15;
    case Moves::kThunderPunch:
      return 15;
    case Moves::kThunderShock:
      return 30;
    case Moves::kToxic:
      return 10;
    case Moves::kTransform:
      return 10;
    case Moves::kTriAttack:
      return 10;
    case Moves::kTwineedle:
      return 20;
    case Moves::kViceGrip:
      return 30;
    case Moves::kVineWhip:
      return 10;
    case Moves::kWaterGun:
      return 25;
    case Moves::kWaterfall:
      return 15;
    case Moves::kWhirlwind:
      return 20;
    case Moves::kWingAttack:
      return 35;
    case Moves::kWithdraw:
      return 40;
    case Moves::kWrap:
      return 20;
    case Moves::kPass:
      return kUnlimited;
    case Moves::kSwitch1:
      return kUnlimited;
    case Moves::kSwitch2:
      return kUnlimited;
    case Moves::kSwitch3:
      return kUnlimited;
    case Moves::kSwitch4:
      return kUnlimited;
    case Moves::kSwitch5:
      return kUnlimited;
    case Moves::kSwitch6:
      return kUnlimited;
    case Moves::kHitSelf:
      return kUnlimited;
    default:
      assert(false);
  };
}

} //namespace artificialtrainer