//
// Created by neel on 1/26/19.
//

#include "type.h"

namespace artificialtrainer {
auto Type(const MoveNames &move_name) -> TypesNames {
  switch (move_name) {
    case MoveNames::kBarrage:
    case MoveNames::kBide:
    case MoveNames::kBind:
    case MoveNames::kBite:
    case MoveNames::kBodySlam:
    case MoveNames::kCometPunch:
    case MoveNames::kConstrict:
    case MoveNames::kConversion:
    case MoveNames::kCut:
    case MoveNames::kDefenseCurl:
    case MoveNames::kDisable:
    case MoveNames::kDizzyPunch:
    case MoveNames::kDoubleTeam:
    case MoveNames::kDoubleEdge:
    case MoveNames::kDoubleSlap:
    case MoveNames::kEggBomb:
    case MoveNames::kExplosion:
    case MoveNames::kFlash:
    case MoveNames::kFocusEnergy:
    case MoveNames::kFuryAttack:
    case MoveNames::kFurySwipes:
    case MoveNames::kGlare:
    case MoveNames::kGrowl:
    case MoveNames::kGrowth:
    case MoveNames::kGuillotine:
    case MoveNames::kGust:
    case MoveNames::kHarden:
    case MoveNames::kHeadbutt:
    case MoveNames::kHornAttack:
    case MoveNames::kHornDrill:
    case MoveNames::kHyperBeam:
    case MoveNames::kHyperFang:
    case MoveNames::kKarateChop:
    case MoveNames::kLeer:
    case MoveNames::kLovelyKiss:
    case MoveNames::kMegaKick:
    case MoveNames::kMegaPunch:
    case MoveNames::kMetronome:
    case MoveNames::kMimic:
    case MoveNames::kMinimize:
    case MoveNames::kPayDay:
    case MoveNames::kPound:
    case MoveNames::kQuickAttack:
    case MoveNames::kRage:
    case MoveNames::kRazorWind:
    case MoveNames::kRecover:
    case MoveNames::kRoar:
    case MoveNames::kScratch:
    case MoveNames::kScreech:
    case MoveNames::kSelfDestruct:
    case MoveNames::kSharpen:
    case MoveNames::kSing:
    case MoveNames::kSkullBash:
    case MoveNames::kSlam:
    case MoveNames::kSlash:
    case MoveNames::kSmokescreen:
    case MoveNames::kSoftBoiled:
    case MoveNames::kSonicBoom:
    case MoveNames::kSpikeCannon:
    case MoveNames::kSplash:
    case MoveNames::kStomp:
    case MoveNames::kStrength:
    case MoveNames::kStruggle:
    case MoveNames::kSubstitute:
    case MoveNames::kSuperFang:
    case MoveNames::kSupersonic:
    case MoveNames::kSwift:
    case MoveNames::kSwordsDance:
    case MoveNames::kTackle:
    case MoveNames::kTailWhip:
    case MoveNames::kTakeDown:
    case MoveNames::kThrash:
    case MoveNames::kTransform:
    case MoveNames::kTriAttack:
    case MoveNames::kViceGrip:
    case MoveNames::kWhirlwind:
    case MoveNames::kWrap:
      return TypesNames::kNormal;
    case MoveNames::kCounter:
    case MoveNames::kDoubleKick:
    case MoveNames::kHighJumpKick:
    case MoveNames::kJumpKick:
    case MoveNames::kLowKick:
    case MoveNames::kRollingKick:
    case MoveNames::kSeismicToss:
    case MoveNames::kSubmission:
      return TypesNames::kFighting;
    case MoveNames::kDrillPeck:
    case MoveNames::kFly:
    case MoveNames::kMirrorMove:
    case MoveNames::kPeck:
    case MoveNames::kSkyAttack:
    case MoveNames::kWingAttack:
      return TypesNames::kFlying;
    case MoveNames::kAcid:
    case MoveNames::kAcidArmor:
    case MoveNames::kPoisonGas:
    case MoveNames::kPoisonSting:
    case MoveNames::kPoisonPowder:
    case MoveNames::kSludge:
    case MoveNames::kSmog:
    case MoveNames::kToxic:
      return TypesNames::kPoison;
    case MoveNames::kBoneClub:
    case MoveNames::kBonemerang:
    case MoveNames::kDig:
    case MoveNames::kEarthquake:
    case MoveNames::kFissure:
    case MoveNames::kSandAttack:
      return TypesNames::kGround;
    case MoveNames::kRockSlide:
    case MoveNames::kRockThrow:
      return TypesNames::kRock;
    case MoveNames::kLeechLife:
    case MoveNames::kPinMissile:
    case MoveNames::kStringShot:
    case MoveNames::kTwineedle:
      return TypesNames::kBug;
    case MoveNames::kConfuseRay:
    case MoveNames::kLick:
    case MoveNames::kNightShade:
      return TypesNames::kGhost;
    case MoveNames::kEmber:
    case MoveNames::kFireBlast:
    case MoveNames::kFirePunch:
    case MoveNames::kFireSpin:
    case MoveNames::kFlamethrower:
      return TypesNames::kFire;
    case MoveNames::kBubble:
    case MoveNames::kBubbleBeam:
    case MoveNames::kClamp:
    case MoveNames::kCrabhammer:
    case MoveNames::kHydroPump:
    case MoveNames::kSurf:
    case MoveNames::kWaterGun:
    case MoveNames::kWaterfall:
    case MoveNames::kWithdraw:
      return TypesNames::kWater;
    case MoveNames::kAbsorb:
    case MoveNames::kLeechSeed:
    case MoveNames::kMegaDrain:
    case MoveNames::kPetalDance:
    case MoveNames::kRazorLeaf:
    case MoveNames::kSleepPowder:
    case MoveNames::kSolarBeam:
    case MoveNames::kSpore:
    case MoveNames::kStunSpore:
    case MoveNames::kVineWhip:
      return TypesNames::kGrass;
    case MoveNames::kThunder:
    case MoveNames::kThunderWave:
    case MoveNames::kThunderbolt:
    case MoveNames::kThunderPunch:
    case MoveNames::kThunderShock:
      return TypesNames::kElectric;
    case MoveNames::kAgility:
    case MoveNames::kAmnesia:
    case MoveNames::kBarrier:
    case MoveNames::kConfusion:
    case MoveNames::kDreamEater:
    case MoveNames::kHypnosis:
    case MoveNames::kKinesis:
    case MoveNames::kLightScreen:
    case MoveNames::kMeditate:
    case MoveNames::kPsybeam:
    case MoveNames::kPsychic:
    case MoveNames::kPsywave:
    case MoveNames::kReflect:
    case MoveNames::kRest:
    case MoveNames::kTeleport:
      return TypesNames::kPsychic;
    case MoveNames::kAuroraBeam:
    case MoveNames::kBlizzard:
    case MoveNames::kHaze:
    case MoveNames::kIceBeam:
    case MoveNames::kIcePunch:
    case MoveNames::kMist:
      return TypesNames::kIce;
    case MoveNames::kDragonRage:
      return TypesNames::kDragon;
    default:
      return TypesNames::kNoType;
  };
}

} //namespace artificialtrainer